### ISSUE TITLE
Force update and or wake up the car with a service call

### ISSUE THREAD

**Issue by EvTheFuture** [zabuldon/teslajsonpy#119]
I'm currently working on an appdaemon app that uses this integration in order to start charging when the utility rate is at the lowest and stop it when it's high.

Are there any way today to force an update of data from the car?

For example, if I want to know how long time it will take to charge the car I simply start charging and wait until I get information on the sensor indicating charge rate and also time remaining.

Since this can take some time to refresh after charging has been started I'd like to force an update after say 30 seconds or so.

Is this already possible? Otherwise I'm thinking of implementing this most likely by adding a service (force update/wake up or similar) and would appreciate some input/feedback/thoughts regarding this or if anyone have another idea on how this can be solved?

**Comment by alandtse** [comment]
Any command will wake the car. The integration checks every minute to see if any car has woken up to refresh its data.

**Comment by tobbensoft** [comment]
Yes, but charging data is polled on the interval set in integration configuration?  11mins..

That is a little long for this situation..

**Comment by alandtse** [comment]
No. 11 minutes is between successful polls. If a car has been asleep it won't have any successful polls until it is awake.

**Comment by tobbensoft** [comment]
Yes, but if you set charge switch to on, it will be about 11 minuts until you get the new data.

**Comment by alandtse** [comment]
That's not how the code is written, but if you want to submit a bug report you know how to do it.

**Comment by tobbensoft** [comment]
I was probably not clear in my description..  It polls after switch is set (and car wakes up)..   All as intended :)

But in the case above that is right after charge switch is set and the "time left" is not stable yet. 

Will it be accepted if @EvTheFuture or someone else implement a service that will trigger a poll if needed to get updated data?

**Comment by alandtse** [comment]
I don't know if HA will accept that service call but I don't have a problem with it.

**Comment by EvTheFuture** [comment]
@alandtse Do you have any other suggestions on how to solve this other than a service call? I just want to rule out so there's not a great idea that I miss before start working.

**Comment by alandtse** [comment]
@EvTheFuture I thought you said waking up the call with a command was enough. That feature is already implemented. Once a car is awake and charging, it will scan at whatever scan interval you have selected until it stop charging, then it'll try to put the car to sleep by going to 660 seconds.

**Comment by EvTheFuture** [comment]
@alandtse now when having an explanation on how it works today, the service would wake the car (if not already awake) and refresh data without waiting for the interval given in the integration (assuming the interval you're talking about is the default 660 when configuring the integration). If the car is already awake, just refresh the values.

**Comment by alandtse** [comment]
As the wakeup code already exists as you mentioned, that's done. You can always just send a lock command or something that would be harmless. If the problem is you can't wait for the next scheduled update within the next 60 seconds, then you'll have to submit a PR to detect a car has come online and then force an immediate update `controller.update(force=True)`. Easiest place would be in the wake_up wrapper after you've sent the actual command that caused the wakeup.

If you want a force refresh at anytime as separate service, then you can submit a PR to HA as you can already force a refresh in the api using the `controller.update(force=True)`. I don't know if any integrations have such a service so I don't know if they'd accept it. Please note that force updates will not wake a car up if it's sleeping to avoid battery drains. Please also make sure any PR handles multiple cars. You don't want to force awake every car that may be on an account.

**Comment by EvTheFuture** [comment]
> You can always just send a lock command or something that would be harmless.

This was my first thought before submitting this issue. However I find it to be a bit of a hack and not very clean. 

I'll do some testing and see what will be the best and most clean way to implement this and I'll make a PR if I come through with something good.

Thanks for your feedback.

**Comment by alandtse** [comment]
This is implemented via `controller.api` using [`WAKE_UP`](https://github.com/zabuldon/teslajsonpy/blob/dev/teslajsonpy/endpoints.json#L47-L51)
