### ISSUE TITLE
Feature request: Homelink support for HA (already WIP in fork)

### ISSUE THREAD

**Issue by carleeno** [zabuldon/teslajsonpy#295]
Hi!
I'm a first time (potential) contributor and wanted to start a discussion and ask some questions before submitting a PR out of the blue.

Now that we have the ButtonEntity in HA, those of us using Tesla's homelink to turn our dumb garage doors into smart garage doors might finally be able to control them in HA.
Related PR #296 
Related tesla_custom integration (draft) PR [here](https://github.com/alandtse/tesla/pull/168)

I have some open questions before I submit a PR though:
- It seems that since opening a garage door is a security item, maybe lock is better than button since extra security measures are built-in to the lock entity. However it'd be pretty cludgy since there's no way to determine or report locked/unlocked and the button will always say "Unlock". This statelessness is why I started with a button entity. Is this ok?
- It gets around the api requirement to have a location value within range of the vehicle by providing the vehicle's own location value. This is the same approach that teslascope uses for it's homelink api call. I think many would value the convenience of the feature over the risk of opening/closing the door when not nearby (plus most if not all powered garage doors have trip and load sensors). However if this would block the feature-add, maybe we can work around this by providing the location from the user's device tracker location from HA via an argument. However this means it can't be remotely triggered, or triggered by a user without a tracker/location. (edit, I'm not sure this workaround is possible as I'm not sure how one would send args with a button entity). Is this ok to allow remotely triggering homelink?
- I'm able to test it with my car which has homelink (and should be done real-world testing later today). I implemented entity availability based on homelink info from the car's state, but I can't test for a vehicle which does not have the homelink device installed at all. Is there someone here who could help test that case?
- Are there any other concerns with adding this entity outside of what I already mentioned?

Thanks!

**Comment by alandtse** [comment]
Hi! Thanks for offering to contribute. It helps since I'm not doing any feature development really.

> Now that we have the ButtonEntity in HA, those of us using Tesla's homelink to turn our dumb garage doors into smart garage doors might finally be able to control them in HA. (edit: still draft) PR #296 Related tesla_custom integration (draft) PR [here](https://github.com/alandtse/tesla/pull/168)
> 
> I have some open questions before I submit a PR though:
> 
> * It seems that since opening a garage door is a security item, maybe lock is better than button since extra security measures are built-in to the lock entity. However it'd be pretty cludgy since there's no way to determine or report locked/unlocked and the button will always say "Unlock". This statelessness is why I started with a button entity. Is this ok?

Button seems most appropriate. I don't think we should repurpose lock for the reasons you mentioned.

> * It gets around the api requirement to have a location value within range of the vehicle by providing the vehicle's own location value. This is the same approach that teslascope uses for it's homelink api call. I think many would value the convenience of the feature over the risk of opening/closing the door when not nearby (plus most if not all powered garage doors have trip and load sensors). However if this would block the feature-add, maybe we can work around this by providing the location from the user's device tracker location from HA via an argument. However this means it can't be remotely triggered, or triggered by a user without a tracker/location. (edit, I'm not sure this workaround is possible as I'm not sure how one would send args with a button entity). Is this ok to allow remotely triggering homelink?

This is fine. Other garage covers actually don't have location verification so it's not that odd. I know HA was moving toward allowing drop downs for entities in options so perhaps in the future there can be an option to select what entity to send location coords from.

> * I'm able to test it with my car which has homelink (and should be done real-world testing later today). I implemented entity availability based on homelink info from the car's state, but I can't test for a vehicle which does not have the homelink device installed at all. Is there someone here who could help test that case?

I have two Teslas one with homelink and one without. I can let you know the values returned so you could check to see if homelink is available and give a reasonable error. Just let me know what json value you need to see.

> * Are there any other concerns with adding this entity outside of what I already mentioned?

No; I'm not doing feature development but there's probably some old issues where people asked for it. Obviously, it'd be nice if you stuck around to help debug issues with the new feature or to help develop it further, but assuming your code passes basic functionality tests, I'm happy for any help.

**Comment by carleeno** [comment]
Thanks @alandtse, I'm glad to help and of course will help debug issues with this when/if they come up (I'll be using it heavily myself as well). It's also presenting as a good learning experience for me.

For your car without homelink, I'm curious if it still has the `homelink_device_count` and/or `homelink_nearby` key in vehicle state. If not I probably should use `.get()` to avoid a potential keyerror...or maybe I should do that regardless?

**Comment by alandtse** [comment]
It's always best to use a get unless you're positive it can't miss the key.

**Comment by alandtse** [comment]
I'd suggest trying the HA contribution since we're not the only integration that might have this issue so it'd help more people; it probably should be an architecture or front end question to start. 

This is also a larger issue you'll see when any command may not be instant. For example for Tesla, if the cars are asleep, it'll take at least 15 seconds to wake up the car and issue the command. That said, I don't mind having it for this commit but I'd ask you to be ready to take it out if HA ever adds some better native `working` state.

> For your car without homelink, I'm curious if it still has the `homelink_device_count` and/or `homelink_nearby` key in vehicle state. If not I probably should use `.get()` to avoid a potential keyerror...or maybe I should do that regardless?

This is to confirm that these keys only exist if the homelink package is installed in the vehicle.

**Comment by carleeno** [comment]
> I'd suggest trying the HA contribution since we're not the only integration that might have this issue so it'd help more people; it probably should be an architecture or front end question to start.
> 
> This is also a larger issue you'll see when any command may not be instant. For example for Tesla, if the cars are asleep, it'll take at least 15 seconds to wake up the car and issue the command. That said, I don't mind having it for this commit but I'd ask you to be ready to take it out if HA ever adds some better native `working` state.
Sounds good, I agree it'd be nice to have for all buttons and I'd definitely be ready to undo this custom disabling for homelink if HA adds a better solution.
> 
> > For your car without homelink, I'm curious if it still has the `homelink_device_count` and/or `homelink_nearby` key in vehicle state. If not I probably should use `.get()` to avoid a potential keyerror...or maybe I should do that regardless?
> 
> This is to confirm that these keys only exist if the homelink package is installed in the vehicle.
Thanks, I'll add one more test to ensure it works as expected in case the keys are missing.
