### ISSUE TITLE
Add support for Tesla Solar

### ISSUE THREAD

**Issue by JoshuaSG** [zabuldon/teslajsonpy#49]
I was thinking about adding support for Tesla Solar, it would be nice to pull the current status of my solar system and then integrate it into Home Assistant.

It looks like you might be in the middle of refactoring, should I wait a bit before I start digging in, or go ahead and attempt something.

**Comment by alandtse** [comment]
We should be refactored now to async if you want to start adding.

**Comment by ocalvo** [comment]
I would love to see this implemented.
How can I help?

**Comment by JoshuaSG** [comment]
Sorry I haven't had time to work on this, Python is a new language to me so I've been meaning to study up on a it. If you know Python I could point you in the right direction on the Tesla API endpoints.

**Comment by hobbe** [comment]
In this context, there is a Tesla Powerwall integration coming to HA: https://github.com/home-assistant/core/pull/32851

**Comment by alandtse** [comment]
I'll close this now that the [Powerwall integration](https://www.home-assistant.io/integrations/powerwall/) exists. That's a synchronous library, so if there was interest in merging it here, I wouldn't be opposed. But one reason it makes sense to be a different library is that manages to do  work locally while this component requires hitting Tesla's actual servers. I'm not sure if there's added benefit to have the connection to Tesla.

**Comment by alandtse** [comment]
Ok, didn't realize there was a use case like that. I'll reopen. I don't have Tesla solar so while it shouldn't be hard to add the API calls, I wouldn't be able to test it and integrate it into HA. 

One place to look is at [tesla_api](https://github.com/mlowijs/tesla_api/blob/master/tesla_api/energy.py) which has mapped out the functions. You'd have to convert their calls to use our `connection.py` since that handles the login automatically.

Here is how I'd approach this.

1. Make sure the basic API calls exist using tesla_api as a guide. Right now we've actually embedded them in our controller component. The controller.py is the brains of the current architecture that controls the connection to the API to try to avoid overloading it.
2. Create solar specific entities to process the data collected from the controller. Right now, the component basically creates entities that are directly imported into HA. This is the confusing part for most people looking at this library in that we've basically moved all the intelligence from the HA component into this library.  All the current entities used in HA are part of the [vehicle entity](https://github.com/zabuldon/teslajsonpy/blob/dev/teslajsonpy/vehicle.py)
3. Modify the component in HA so it will load whatever you've generated in 2.

**Comment by nomer** [comment]
I'm familiar with python as well as the Tesla API, but new to Home Assistant development. 

I'd like to attempt adding solar support but wondering the best way to approach it. It seems that the Controller is modeled closely to vehicles and extending it with solar attributes could prove difficult. 

I'm thinking the best approach might be to create a separate controller to handle the solar endpoints and attributes. That would mean the Tesla component would have to manage two controllers, right? Are there any other drawbacks going this route?

**Comment by alandtse** [comment]
Two controllers could work but the controller is responsible for rate limiting and backend state. The controller is responsible with updating all the back end json data and then each component is supposed to read it. The issue we have is each component exists in the library and then essentially is exposed in HA. This makes it a pain to maintain the library since changes have to happen in both repositories. I've been meaning to move everything out of the library and into HA proper so changes to HA can be isolated. All I've done so far is to move most of the components into the ha directory.

I would suggest building the solar components in HA and leaving this library for direct calls to the API. If you need to hit a new end point, that's the only case where you need to update the library. Review the library components to see how you should call the library.

**Comment by mcolyer** [comment]
@nomer did you end up starting on this? I'm interested in figuring this out as well to add support for the [new energy monitoring](https://www.home-assistant.io/blog/2021/08/04/home-energy-management/).
